"""Add Gemini Live fields to ImageDiagnosis

Revision ID: a6fec7118e18
Revises: aaa459dbc2ff
Create Date: 2026-06-30 14:23:13.963739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fec7118e18'
down_revision: Union[str, Sequence[str], None] = 'aaa459dbc2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.add_column('image_diagnoses', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('image_diagnoses', sa.Column('health_status', sa.String(length=100), nullable=True))
    op.add_column('image_diagnoses', sa.Column('farmer_summary', sa.Text(), nullable=True))
    op.add_column('image_diagnoses', sa.Column('natural_remedies_json', sa.Text(), nullable=True))
    op.add_column('image_diagnoses', sa.Column('organic_fertilizer_suggestions_json', sa.Text(), nullable=True))
    op.add_column('image_diagnoses', sa.Column('preventive_care_json', sa.Text(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_column('image_diagnoses', 'preventive_care_json')
    op.drop_column('image_diagnoses', 'organic_fertilizer_suggestions_json')
    op.drop_column('image_diagnoses', 'natural_remedies_json')
    op.drop_column('image_diagnoses', 'farmer_summary')
    op.drop_column('image_diagnoses', 'health_status')
    op.drop_column('image_diagnoses', 'language')
    pass
    # ### end Alembic commands ###
