"""Add ImageDiagnosis model

Revision ID: fd7838c6fc39
Revises: 6c067a6467e9
Create Date: 2026-06-29 21:59:43.561101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7838c6fc39'
down_revision: Union[str, Sequence[str], None] = '6c067a6467e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=False),
    sa.Column('plant_type', sa.String(), nullable=True),
    sa.Column('disease_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('symptoms_json', sa.String(), nullable=True),
    sa.Column('advice_json', sa.String(), nullable=True),
    sa.Column('is_demo_result', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_diagnoses_id'), 'image_diagnoses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_diagnoses_id'), table_name='image_diagnoses')
    op.drop_table('image_diagnoses')
    # ### end Alembic commands ###
